CREATE TABLE COMANDO (
  ID_COMANDO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_TOKEN INTEGER UNSIGNED NULL,
  NOME CHAR(20) NULL,
  TIPO CHAR(20) NULL,
  COMPORTAMENTO CHAR(60) NULL,
  FECHAMENTO CHAR(20) NULL,
  PRIMARY KEY(ID_COMANDO)
);

CREATE TABLE TOKEN (
  ID_TOKEN INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GRUPO CHAR(30) NULL,
  CARACTERES TEXT NULL,
  PRIMARY KEY(ID_TOKEN)
);


